import type { MutationRecipe } from "@/types/garden";

export const MUTATION_RECIPES: Record<string, MutationRecipe> = {
  thumbcorn: {
    parents: ["bakers-wheat", "bakers-wheat"],
    chance: "1%",
    baseChance: 1,
    description: "2x Baker's Wheat adjacents",
    difficulty: "facile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "same_plant",
  },
  bakeberry: {
    parents: ["bakers-wheat", "bakers-wheat"],
    chance: "0.1%",
    baseChance: 0.1,
    description: "2x Baker's Wheat adjacents (très rare)",
    difficulty: "difficile",
    soilStrategy: "Fertilizer → Wood Chips obligatoire",
    layout: "same_plant",
  },
  cronerice: {
    parents: ["bakers-wheat", "thumbcorn"],
    chance: "1%",
    baseChance: 1,
    description: "Baker's Wheat + Thumbcorn adjacents",
    difficulty: "facile",
    soilStrategy:
      "Synchroniser la maturité (Wheat d'abord, attendre 2 ticks, puis Thumbcorn)",
    layout: "adjacent",
  },
  gildmillet: {
    parents: ["thumbcorn", "cronerice"],
    chance: "1%",
    baseChance: 1,
    description: "Thumbcorn + Cronerice adjacents",
    difficulty: "facile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  "brown-mold": {
    parents: ["meddleweed"],
    chance: "19.8%",
    baseChance: 19.8,
    description: "Récolte MANUELLE de Meddleweed vieux (chance = âge × 0.2%)",
    difficulty: "spécial",
    soilStrategy:
      "1) Fertilizer pour croissance → 2) Clay pour vieillissement → 3) Récolte manuelle à âge 99",
    layout: "manual_harvest",
  },
  crumbspore: {
    parents: ["meddleweed"],
    chance: "19.8%",
    baseChance: 19.8,
    description:
      "Récolte MANUELLE de Meddleweed vieux (même méthode que Brown Mold)",
    difficulty: "spécial",
    soilStrategy:
      "1) Fertilizer pour croissance → 2) Clay pour vieillissement → 3) Récolte manuelle à âge 99",
    layout: "manual_harvest",
  },
  "white-mildew": {
    parents: ["brown-mold"],
    chance: "7%",
    baseChance: 7,
    description: "1 SEUL Brown Mold mature - auto-mutation sur lui-même",
    difficulty: "facile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "single",
  },
  "ordinary-clover": {
    parents: ["bakers-wheat", "gildmillet"],
    chance: "3%",
    baseChance: 3,
    description: "Baker's Wheat + Gildmillet adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  chocoroot: {
    parents: ["bakers-wheat", "brown-mold"],
    chance: "2.5%",
    baseChance: 2.5,
    description: "Baker's Wheat + Brown Mold adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  "white-chocoroot": {
    parents: ["chocoroot", "white-mildew"],
    chance: "2%",
    baseChance: 2,
    description: "Chocoroot + White Mildew adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  doughshroom: {
    parents: ["crumbspore", "crumbspore"],
    chance: "0.5%",
    baseChance: 0.5,
    description: "2x Crumbspore adjacents",
    difficulty: "difficile",
    soilStrategy: "Fertilizer → Wood Chips obligatoire",
    layout: "same_plant",
  },
  "green-rot": {
    parents: ["ordinary-clover", "white-mildew"],
    chance: "1%",
    baseChance: 1,
    description: "Ordinary Clover + White Mildew adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  shimmerlily: {
    parents: ["gildmillet", "ordinary-clover"],
    chance: "0.2%",
    baseChance: 0.2,
    description: "Gildmillet + Ordinary Clover adjacents",
    difficulty: "très difficile",
    soilStrategy: "Fertilizer → Wood Chips obligatoire, beaucoup de patience",
    layout: "adjacent",
  },
  wrinklegill: {
    parents: ["brown-mold", "crumbspore"],
    chance: "1%",
    baseChance: 1,
    description: "Brown Mold + Crumbspore adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  wardlichen: {
    parents: ["cronerice", "white-mildew"],
    chance: "1%",
    baseChance: 1,
    description: "Cronerice + White Mildew adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  keenmoss: {
    parents: ["wardlichen"],
    chance: "7%",
    baseChance: 7,
    description: "1 SEUL Wardlichen mature - auto-mutation sur lui-même",
    difficulty: "facile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "single",
  },
  tidygrass: {
    parents: ["bakers-wheat", "white-chocoroot"],
    chance: "2%",
    baseChance: 2,
    description: "Baker's Wheat + White Chocoroot adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  elderwort: {
    parents: ["shimmerlily", "cronerice"],
    chance: "0.2%",
    baseChance: 0.2,
    description: "Shimmerlily + Cronerice adjacents",
    difficulty: "très difficile",
    soilStrategy: "Fertilizer → Wood Chips obligatoire, très long",
    layout: "adjacent",
  },
  whiskerbloom: {
    parents: ["shimmerlily", "white-mildew"],
    chance: "1%",
    baseChance: 1,
    description: "Shimmerlily + White Mildew adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  nursetulip: {
    parents: ["whiskerbloom", "whiskerbloom"],
    chance: "5%",
    baseChance: 5,
    description: "2x Whiskerbloom adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "same_plant",
  },
  chimerose: {
    parents: ["shimmerlily", "elderwort"],
    chance: "0.5%",
    baseChance: 0.5,
    description: "Shimmerlily + Elderwort adjacents",
    difficulty: "difficile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  drowsyfern: {
    parents: ["chocoroot", "keenmoss"],
    chance: "1%",
    baseChance: 1,
    description: "Chocoroot + Keenmoss adjacents",
    difficulty: "modéré",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  queenbeet: {
    parents: ["bakeberry", "chocoroot"],
    chance: "0.1%",
    baseChance: 0.1,
    description: "Bakeberry + Chocoroot adjacents",
    difficulty: "extrêmement difficile",
    soilStrategy:
      "Fertilizer → Wood Chips obligatoire, puis Clay pour conservation",
    layout: "adjacent",
  },
  glovemorel: {
    parents: ["doughshroom", "elderwort"],
    chance: "0.5%",
    baseChance: 0.5,
    description: "Doughshroom + Elderwort adjacents",
    difficulty: "difficile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  cheapcap: {
    parents: ["doughshroom", "shimmerlily"],
    chance: "0.5%",
    baseChance: 0.5,
    description: "Doughshroom + Shimmerlily adjacents",
    difficulty: "difficile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  "fools-bolete": {
    parents: ["doughshroom", "green-rot"],
    chance: "0.5%",
    baseChance: 0.5,
    description: "Doughshroom + Green Rot adjacents",
    difficulty: "difficile",
    soilStrategy: "Fertilizer → Wood Chips",
    layout: "adjacent",
  },
  ichorpuff: {
    parents: ["elderwort", "crumbspore"],
    chance: "0.2%",
    baseChance: 0.2,
    description: "Elderwort + Crumbspore adjacents",
    difficulty: "très difficile",
    soilStrategy: "Fertilizer → Wood Chips obligatoire",
    layout: "adjacent",
  },
  "golden-clover": {
    parents: [
      "ordinary-clover",
      "ordinary-clover",
      "ordinary-clover",
      "ordinary-clover",
    ],
    chance: "1.83%",
    baseChance: 1.83,
    description: "Configuration spéciale Ordinary Clover (Level 6 Garden)",
    difficulty: "cauchemar",
    soilStrategy: "Wood Chips obligatoire, maintenance complexe",
    layout: "golden_clover",
  },
  duketater: {
    parents: ["queenbeet", "elderwort"],
    chance: "0.1%",
    baseChance: 0.1,
    description: "Configuration complexe Queenbeet + Elderwort",
    difficulty: "cauchemar",
    soilStrategy: "Très avancé, pattern spécial",
    layout: "adjacent",
  },
  shriekbulb: {
    parents: ["duketater", "duketater", "duketater"],
    chance: "10 plants possible",
    baseChance: 0.1,
    description:
      "Pattern en damier avec Duketater/Elderwort (Level 6: 10 mutations possibles)",
    difficulty: "cauchemar",
    soilStrategy: "Pebbles pour immortalité, configuration en damier",
    layout: "shriekbulb",
  },
  everdaisy: {
    parents: [
      "tidygrass",
      "tidygrass",
      "tidygrass",
      "elderwort",
      "elderwort",
      "elderwort",
    ],
    chance: "0.2%",
    baseChance: 0.2,
    description: "Lignes alternées: Tidygrass / vide / Elderwort / vide",
    difficulty: "cauchemar",
    soilStrategy:
      "Pattern alterné très spécifique, immortel quand entouré de fleurs",
    layout: "everdaisy",
  },
  "juicy-queenbeet": {
    parents: [
      "queenbeet",
      "queenbeet",
      "queenbeet",
      "queenbeet",
      "queenbeet",
      "queenbeet",
      "queenbeet",
      "queenbeet",
    ],
    chance: "0.001%",
    baseChance: 0.001,
    description:
      "8x Queenbeet en cercle parfait autour d'une case vide (plusieurs cercles possibles)",
    difficulty: "impossible",
    soilStrategy: "Tous matures en même temps, peut prendre des semaines",
    layout: "juicy_queenbeet",
  },
};
