import type { Seed } from "@/types/garden";

export const SEEDS_DATA: Record<string, Seed> = {
  "bakers-wheat": {
    key: "bakers-wheat",
    name: "Baker's Wheat",
    emoji: "🌾",
    type: "plant",
    rarity: "starter",
    maturity: 5,
    effect: "+1% CpS",
  },
  meddleweed: {
    key: "meddleweed",
    name: "Meddleweed",
    emoji: "🌿",
    type: "fungus",
    rarity: "starter",
    maturity: 5,
    effect: "Spawns naturally, can contaminate",
  },
  thumbcorn: {
    key: "thumbcorn",
    name: "Thumbcorn",
    emoji: "🌽",
    type: "plant",
    rarity: "common",
    maturity: 3,
    effect: "+2% cookies per click",
  },
  cronerice: {
    key: "cronerice",
    name: "Cronerice",
    emoji: "🌾",
    type: "plant",
    rarity: "common",
    maturity: 5,
    effect: "+3% grandma CpS",
  },
  bakeberry: {
    key: "bakeberry",
    name: "Bakeberry",
    emoji: "🫐",
    type: "plant",
    rarity: "uncommon",
    maturity: 8,
    effect: "+1% CpS, harvest bonus",
  },
  gildmillet: {
    key: "gildmillet",
    name: "Gildmillet",
    emoji: "🌾",
    type: "plant",
    rarity: "uncommon",
    maturity: 6,
    effect: "+1% golden cookie gains, +0.1% duration",
  },
  "brown-mold": {
    key: "brown-mold",
    name: "Brown Mold",
    emoji: "🍄",
    type: "fungus",
    rarity: "uncommon",
    maturity: 3,
    effect: "-1% CpS, can spread",
  },
  crumbspore: {
    key: "crumbspore",
    name: "Crumbspore",
    emoji: "🍄",
    type: "fungus",
    rarity: "uncommon",
    maturity: 4,
    effect: "Can contaminate, harvest bonus",
  },
  "white-mildew": {
    key: "white-mildew",
    name: "White Mildew",
    emoji: "🦠",
    type: "fungus",
    rarity: "uncommon",
    maturity: 3,
    effect: "+1% CpS",
  },
  "ordinary-clover": {
    key: "ordinary-clover",
    name: "Ordinary Clover",
    emoji: "🍀",
    type: "plant",
    rarity: "uncommon",
    maturity: 5,
    effect: "+1% golden cookie frequency",
  },
  chocoroot: {
    key: "chocoroot",
    name: "Chocoroot",
    emoji: "🥔",
    type: "plant",
    rarity: "rare",
    maturity: 6,
    effect: "+1% CpS, harvest bonus",
  },
  "white-chocoroot": {
    key: "white-chocoroot",
    name: "White Chocoroot",
    emoji: "🥔",
    type: "plant",
    rarity: "rare",
    maturity: 6,
    effect: "+1% golden cookie gains, harvest bonus",
  },
  doughshroom: {
    key: "doughshroom",
    name: "Doughshroom",
    emoji: "🍄",
    type: "fungus",
    rarity: "rare",
    maturity: 6,
    effect: "+1% CpS",
  },
  "green-rot": {
    key: "green-rot",
    name: "Green Rot",
    emoji: "🦠",
    type: "fungus",
    rarity: "rare",
    maturity: 4,
    effect: "+1% golden cookie frequency, +1% random drops",
  },
  shimmerlily: {
    key: "shimmerlily",
    name: "Shimmerlily",
    emoji: "🌸",
    type: "plant",
    rarity: "rare",
    maturity: 7,
    effect: "+1% golden cookie gains & frequency",
  },
  wrinklegill: {
    key: "wrinklegill",
    name: "Wrinklegill",
    emoji: "🍄",
    type: "fungus",
    rarity: "rare",
    maturity: 5,
    effect: "Wrinklers spawn 2% faster, digest 1% more",
  },
  wardlichen: {
    key: "wardlichen",
    name: "Wardlichen",
    emoji: "🦠",
    type: "fungus",
    rarity: "rare",
    maturity: 8,
    effect: "-2% wrath cookies, wrinklers spawn 15% slower",
  },
  keenmoss: {
    key: "keenmoss",
    name: "Keenmoss",
    emoji: "🌿",
    type: "fungus",
    rarity: "rare",
    maturity: 6,
    effect: "+3% random drops",
  },
  tidygrass: {
    key: "tidygrass",
    name: "Tidygrass",
    emoji: "🌱",
    type: "plant",
    rarity: "rare",
    maturity: 4,
    effect: "Prevents weeds/fungi in 5×5 area",
  },
  elderwort: {
    key: "elderwort",
    name: "Elderwort",
    emoji: "🌿",
    type: "plant",
    rarity: "rare",
    maturity: 0,
    effect: "+1% wrath cookies, immortal, speeds aging",
  },
  whiskerbloom: {
    key: "whiskerbloom",
    name: "Whiskerbloom",
    emoji: "🌺",
    type: "plant",
    rarity: "rare",
    maturity: 7,
    effect: "+1% CpS",
  },
  nursetulip: {
    key: "nursetulip",
    name: "Nursetulip",
    emoji: "🌷",
    type: "plant",
    rarity: "rare",
    maturity: 5,
    effect: "Boosts nearby plants by 20%",
  },
  chimerose: {
    key: "chimerose",
    name: "Chimerose",
    emoji: "🌹",
    type: "plant",
    rarity: "rare",
    maturity: 7,
    effect: "+1% CpS",
  },
  drowsyfern: {
    key: "drowsyfern",
    name: "Drowsyfern",
    emoji: "🌿",
    type: "plant",
    rarity: "rare",
    maturity: 5,
    effect: "+3% CpS while game closed",
  },
  queenbeet: {
    key: "queenbeet",
    name: "Queenbeet",
    emoji: "🥬",
    type: "plant",
    rarity: "epic",
    maturity: 16,
    effect: "-2% CpS, huge harvest bonus",
  },
  glovemorel: {
    key: "glovemorel",
    name: "Glovemorel",
    emoji: "🍄",
    type: "fungus",
    rarity: "epic",
    maturity: 7,
    effect: "+4% click cookies, +1% cursor efficiency, -1% CpS",
  },
  cheapcap: {
    key: "cheapcap",
    name: "Cheapcap",
    emoji: "🍄",
    type: "fungus",
    rarity: "epic",
    maturity: 8,
    effect: "-20% building costs",
  },
  "fools-bolete": {
    key: "fools-bolete",
    name: "Fool's Bolete",
    emoji: "🍄",
    type: "fungus",
    rarity: "epic",
    maturity: 6,
    effect: "+2% golden cookie frequency, -5% gains",
  },
  ichorpuff: {
    key: "ichorpuff",
    name: "Ichorpuff",
    emoji: "🍄",
    type: "fungus",
    rarity: "epic",
    maturity: 8,
    effect: "Slows aging in 3×3, -50% efficiency",
  },
  "golden-clover": {
    key: "golden-clover",
    name: "Golden Clover",
    emoji: "🍀",
    type: "plant",
    rarity: "legendary",
    maturity: 5,
    effect: "+3% golden cookie frequency",
  },
  duketater: {
    key: "duketater",
    name: "Duketater",
    emoji: "🥔",
    type: "plant",
    rarity: "legendary",
    maturity: 24,
    effect: "+4% CpS, 10% chance to survive harvest",
  },
  shriekbulb: {
    key: "shriekbulb",
    name: "Shriekbulb",
    emoji: "🧅",
    type: "plant",
    rarity: "legendary",
    maturity: 8,
    effect: "-2% CpS, plants 5% less efficient in 3×3",
  },
  everdaisy: {
    key: "everdaisy",
    name: "Everdaisy",
    emoji: "🌼",
    type: "plant",
    rarity: "legendary",
    maturity: 10,
    effect: "Immortal when surrounded by flowers",
  },
  "juicy-queenbeet": {
    key: "juicy-queenbeet",
    name: "Juicy Queenbeet",
    emoji: "🥬",
    type: "plant",
    rarity: "legendary",
    maturity: 32,
    effect: "Cannot be planted, +1 sugar lump when sacrificing",
  },
};

export const ALL_SEEDS = [
  "bakers-wheat",
  "meddleweed",
  "thumbcorn",
  "cronerice",
  "bakeberry",
  "gildmillet",
  "brown-mold",
  "crumbspore",
  "white-mildew",
  "ordinary-clover",
  "chocoroot",
  "white-chocoroot",
  "doughshroom",
  "green-rot",
  "shimmerlily",
  "wrinklegill",
  "wardlichen",
  "keenmoss",
  "tidygrass",
  "elderwort",
  "whiskerbloom",
  "nursetulip",
  "chimerose",
  "drowsyfern",
  "queenbeet",
  "glovemorel",
  "cheapcap",
  "fools-bolete",
  "ichorpuff",
  "golden-clover",
  "duketater",
  "shriekbulb",
  "everdaisy",
  "juicy-queenbeet",
] as const;
